eureka:
  instance:
    hostname: ${DISCOVERY_NAME:localhost}
  client:
    service-url:
      defaultZone: http://${DISCOVERY_NAME:localhost}:8761/eureka
spring:
  cloud:
    config:
      override.system-properties: false

management:
  tracing:
    sampling:
      probability: 1.0