spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: password
    url: jdbc:postgresql://localhost:5432/payment
    username: iraianbu
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        spring.json.type.mapping: paymentConfirmation:com.iraianbu.ecommerce.body.PaymentNotificationRequest
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer