spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: password
    url: jdbc:postgresql://localhost:5432/product
    username: iraianbu
  flyway:
    baseline-description: '"init"'
    baseline-on-migrate: true
    baseline-version: 0
    enabled: true
    password: ${spring.datasource.password}
    user: ${spring.datasource.username}
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate